Update dev checks 5.2

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -67,16 +67,16 @@ jobs:
       - name: Create network
         run: docker network create to-do-app-network || true
 
-      # - name: Start Postgres service
-      #   working-directory: ./postgres-db
-      #   run: docker compose up -d --build
+      - name: Start Postgres service
+        working-directory: ./postgres-db
+        run: docker compose up -d --build
 
       - name: Check Postgres logs
         run: docker logs postgres-db
 
-      - name: Wait for Postgres to be healthy
-        run: |
-          timeout 120s bash -c 'until [ "$(docker inspect --format="{{.State.Health.Status}}" postgres-db)" = "healthy" ]; do echo "Waiting for Postgres to be healthy..."; sleep 5; done' || { echo "Postgres failed to become healthy within 2 minutes"; exit 1; }
+      # - name: Wait for Postgres to be healthy
+      #   run: |
+      #     timeout 120s bash -c 'until [ "$(docker inspect --format="{{.State.Health.Status}}" postgres-db)" = "healthy" ]; do echo "Waiting for Postgres to be healthy..."; sleep 5; done' || { echo "Postgres failed to become healthy within 2 minutes"; exit 1; }
 
       - name: Start backend and Redis services
         run: docker compose up -d --build todo-app-backend todo-app-redis
