Updated dev-checks 6.1

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -70,9 +70,13 @@ jobs:
         working-directory: ./postgres-db
         run: docker compose up -d --build
 
-      - name: Wait for Postgres to be healthy
+      - name: Check Postgres log
         run: |
-          timeout 120s bash -c 'until [ "$(docker inspect --format="{{.State.Health.Status}}" postgres-db)" = "healthy" ]; do echo "Waiting for Postgres to be healthy..."; sleep 5; done' || { echo "Postgres failed to become healthy within 2 minutes"; exit 1; }
+          docker logs postgres-db
+
+      # - name: Wait for Postgres to be healthy
+      #   run: |
+      #     timeout 120s bash -c 'until [ "$(docker inspect --format="{{.State.Health.Status}}" postgres-db)" = "healthy" ]; do echo "Waiting for Postgres to be healthy..."; sleep 5; done' || { echo "Postgres failed to become healthy within 2 minutes"; exit 1; }
 
       - name: Start backend and Redis services
         run: docker compose up -d --build todo-app-backend todo-app-redis
